module.exports.PURCHASE_CATALOG = {
    PERMIT_14DAY: {
        id: 'PERMIT_14DAY',
        itemID: 238,
        price: 249,
        name: '14 Day Building Permit',
    },
    PERMIT_30DAY: {
        id: 'PERMIT_30DAY',
        itemID: 239,
        price: 499,
        name: '30 Day Building Permit',
    },
    NEW_MONEY_BAG: {
        id: 'NEW_MONEY_BAG',
        itemID: 328,
        price: 200,
        name: 'Cosmetic Money Bag',
    },
    CROWN: {
        id: 'CROWN',
        itemID: 909,
        price: 1,
        name: 'Crown',
        description: 'Crown',
        crownAmount: 1,
    },
    CROWN_2K: {
        id: 'CROWN_2K',
        itemID: 909,
        price: 199,
        name: '2K Crowns',
        description: '2,000 Crowns',
        crownAmount: 2000,
    },
    CROWN_5_5K: {
        id: 'CROWN_5_5K',
        itemID: 909,
        price: 499,
        name: '5.5K Crowns',
        description: '5,000 Crowns\n+ 500 Bonus Crowns',
        crownAmount: 5500,
    },
    CROWN_12K: {
        id: 'CROWN_12K',
        itemID: 909,
        price: 999,
        name: '12K Crowns',
        description: '10,000 Crowns\n+ 2,000 Bonus Crowns',
        crownAmount: 12000,
    },
    CROWN_25K: {
        id: 'CROWN_25K',
        itemID: 909,
        price: 1999,
        name: '25K Crowns',
        description: '20,000 Crowns\n+ 5,000 Bonus Crowns',
        crownAmount: 25000,
    },
    CROWN_75K: {
        id: 'CROWN_75K',
        itemID: 909,
        price: 4999,
        name: '75K Crowns',
        description: '50,000 Crowns\n+ 25,000 Bonus Crowns',
        crownAmount: 75000,
    },
    CROWN_200K: {
        id: 'CROWN_200K',
        itemID: 909,
        price: 9999,
        name: '200K Crowns',
        description: '100,000 Crowns\n+ 100,000 Bonus Crowns',
        crownAmount: 200000,
    },
};

module.exports.CROWN_PURCHASES = [
    this.PURCHASE_CATALOG.CROWN_2K,
    this.PURCHASE_CATALOG.CROWN_5_5K,
    this.PURCHASE_CATALOG.CROWN_12K,
    this.PURCHASE_CATALOG.CROWN_25K,
    this.PURCHASE_CATALOG.CROWN_75K,
    this.PURCHASE_CATALOG.CROWN_200K,
];