module.exports.PURCHASE_CATALOG = {
    PERMIT_14DAY: {
        id: 'PERMIT_14DAY',
        itemID: 238,
        price: 249,
        name: '14 Day Building Permit',
    },
    PERMIT_30DAY: {
        id: 'PERMIT_30DAY',
        itemID: 239,
        price: 499,
        name: '30 Day Building Permit',
    },
    NEW_MONEY_BAG: {
        id: 'NEW_MONEY_BAG',
        itemID: 328,
        price: 200,
        name: 'Cosmetic Money Bag',
    },
    SHARDS_2K: {
        id: 'SHARDS_2K',
        itemID: -1,
        price: 199,
        name: '2K Shards',
        description: '2,000 Shards',
        shardAmount: 2000,
    },
    SHARDS_5_5K: {
        id: 'SHARDS_5_5K',
        itemID: -1,
        price: 499,
        name: '5.5K Shards',
        description: '5,000 Shards\n+ 500 Bonus Shards',
        shardAmount: 5500,
    },
    SHARDS_12K: {
        id: 'SHARDS_12K',
        itemID: -1,
        price: 999,
        name: '12K Shards',
        description: '10,000 Shards\n+ 2,000 Bonus Shards',
        shardAmount: 12000,
    },
    SHARDS_25K: {
        id: 'SHARDS_25K',
        itemID: -1,
        price: 1999,
        name: '25K Shards',
        description: '20,000 Shards\n+ 5,000 Bonus Shards',
        shardAmount: 25000,
    },
    SHARDS_75K: {
        id: 'SHARDS_75K',
        itemID: -1,
        price: 4999,
        name: '75K Shards',
        description: '50,000 Shards\n+ 25,000 Bonus Shards',
        shardAmount: 75000,
    },
    SHARDS_200K: {
        id: 'SHARDS_200K',
        itemID: -1,
        price: 9999,
        name: '200K Shards',
        description: '100,000 Shards\n+ 100,000 Bonus Shards',
        shardAmount: 200000,
    },
};

module.exports.SHARDS_PURCHASES = [
    this.PURCHASE_CATALOG.SHARDS_2K,
    this.PURCHASE_CATALOG.SHARDS_5_5K,
    this.PURCHASE_CATALOG.SHARDS_12K,
    this.PURCHASE_CATALOG.SHARDS_25K,
    this.PURCHASE_CATALOG.SHARDS_75K,
    this.PURCHASE_CATALOG.SHARDS_200K,
];